# Generated by Django 5.2.6 on 2026-02-15 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Description',
            new_name='description',
        ),
    ]
