# Generated by Django 5.2.6 on 2026-02-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_description_review_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
