# Generated by Django 5.2.6 on 2026-02-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comment',
        ),
    ]
