# Generated by Django 5.2.6 on 2026-02-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_review_date_alter_review_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
