# Generated by Django 5.2.6 on 2026-02-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_id'),
        ('product', '0004_rename_description_review_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
